plugins {
    id("com.mikepenz.convention.kotlin-multiplatform")
    id("com.mikepenz.convention.publishing")
    alias(libs.plugins.kotlinSerialization)
}

abstract class VersionTask : Sync() {
    @get:Input
    abstract val packageString: Property<String>

    @get:Input
    abstract val version: Property<String>

    fun store(resourceHandler: ResourceHandler) {
        from(
            resourceHandler.text.fromString(
                """
                    // Autogenerated. Do not edit!
                    package ${packageString.get().trim()}

                    const val A2UI_PROTOCOL_VERSION = "v0.9"
                    const val A2CUI_VERSION = "${version.get()}"
                """.trimIndent().trim()
            )
        ) {
            rename { "Version.kt" }
            into(packageString.get().replace('.', '/'))
        }
    }
}

val appVersion = providers.gradleProperty("VERSION_NAME").get()

val generateVersion = tasks.register<VersionTask>("generateVersion") {
    packageString.set("dev.mikepenz.a2cui.core")
    version.set(appVersion)
    store(resources)
    into(layout.buildDirectory.dir("generated-version/kotlin/"))
}

kotlin {
    android {
        namespace = "dev.mikepenz.a2cui.core"
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generateVersion)
        }
        commonMain.dependencies {
            implementation(libs.kotlinx.serialization.json)
            implementation(baseLibs.kotlinx.coroutines.core)
            api(libs.kermit)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.turbine)
            implementation(libs.kotlinx.coroutines.test)
        }
    }
}
