package dev.mikepenz.a2cui.agui

import dev.mikepenz.a2cui.core.DataModel
import kotlinx.coroutines.channels.BufferOverflow
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.SharedFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asSharedFlow
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonArray
import kotlinx.serialization.json.buildJsonObject

/**
 * Applies AG-UI `STATE_SNAPSHOT` and `STATE_DELTA` events to a [DataModel]. This is the
 * agent-level state channel, separate from A2UI's per-surface data model — apps that use
 * CoAgent-style shared state should instantiate one reducer per logical state store.
 *
 * The reducer also exposes an [outbound] flow of JSON Patches generated by local UI edits
 * (see [writeLocal]); callers forward these to the agent (e.g. by reusing them as the next
 * run's `state` payload, or by emitting them on a custom AG-UI side channel).
 */
public class AguiStateReducer(public val store: DataModel = DataModel()) {

    /** Observable snapshot of the store's root JSON element. */
    public val state: StateFlow<JsonElement> get() = store.root

    private val _outbound = MutableSharedFlow<JsonArray>(
        replay = 0,
        extraBufferCapacity = 64,
        onBufferOverflow = BufferOverflow.SUSPEND,
    )

    /** Patches emitted by local UI edits — forward these to the agent. */
    public val outbound: SharedFlow<JsonArray> = _outbound.asSharedFlow()

    public fun apply(event: AguiEvent) {
        when (event) {
            is AguiEvent.StateSnapshot -> {
                val next = event.snapshot
                store.write(pointer = "", value = next)
            }
            is AguiEvent.StateDelta -> {
                val current = store.snapshot()
                val updated = JsonPatch.apply(current, event.delta)
                store.write(pointer = "", value = updated)
            }
            else -> Unit
        }
    }

    /**
     * Write [value] locally at [pointer] and emit an RFC 6902 `replace` patch on [outbound].
     * Used by `rememberCoAgentState` to flush UI-driven mutations back toward the agent.
     */
    public fun writeLocal(pointer: String, value: JsonElement) {
        store.write(pointer, value)
        val patch = buildJsonArray {
            add(
                buildJsonObject {
                    put("op", JsonPrimitive("replace"))
                    put("path", JsonPrimitive(pointer))
                    put("value", value)
                },
            )
        }
        _outbound.tryEmit(patch)
    }
}
