package dev.mikepenz.a2cui.codegen

import kotlinx.serialization.json.JsonObject

/**
 * Emits the `.kt` source of a generated [dev.mikepenz.a2cui.compose.Catalog] implementation.
 *
 * The generated file has three consumable surfaces:
 *  - `install(registry)` — registers every `@A2uiComponent`-annotated `ComponentFactory`.
 *  - `toJsonSchema()` — returns the catalog's JSON Schema as a parsed `JsonObject`.
 *  - `ToolPromptFragment` — the markdown description intended for the agent's system prompt.
 */
internal object CatalogGenerator {

    fun generate(
        packageName: String,
        className: String,
        catalogId: String,
        specs: List<ComponentSpec>,
        schema: JsonObject,
        promptFragment: String,
    ): String = buildString {
        appendLine("// Generated by :a2cui-codegen — do not edit.")
        appendLine("@file:Suppress(\"RedundantVisibilityModifier\", \"unused\")")
        appendLine()
        if (packageName.isNotEmpty()) {
            appendLine("package $packageName")
            appendLine()
        }
        appendLine("import dev.mikepenz.a2cui.compose.Catalog")
        appendLine("import dev.mikepenz.a2cui.compose.ComponentRegistry")
        appendLine("import kotlinx.serialization.json.Json")
        appendLine("import kotlinx.serialization.json.JsonObject")
        appendLine("import kotlinx.serialization.json.jsonObject")
        appendLine()
        appendLine("public object $className : Catalog {")
        appendLine("    public override val id: String = ${quoted(catalogId)}")
        appendLine()
        appendLine("    public override fun install(registry: ComponentRegistry) {")
        specs.forEach { spec ->
            appendLine("        registry.register(${quoted(spec.name)}, ${spec.factoryReference})")
        }
        appendLine("    }")
        appendLine()
        appendLine("    public override fun toJsonSchema(): JsonObject =")
        appendLine("        Json.parseToJsonElement(RAW_SCHEMA).jsonObject")
        appendLine()
        appendLine("    public val ToolPromptFragment: String = ${tripleQuoted(promptFragment)}")
        appendLine()
        appendLine("    private val RAW_SCHEMA: String = ${tripleQuoted(schema.toString())}")
        appendLine("}")
    }

    private fun quoted(value: String): String = "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\""

    /**
     * Emit a Kotlin raw string literal. Triple-quote avoids escaping JSON/markdown `"` and `\n`.
     * Two hazards to neutralise:
     *  - a literal `"""` in the payload — splice a `${'"'}` in so it can't terminate early, and
     *  - `$identifier` / `${...}` — raw strings still evaluate templates, and JSON Schema keys
     *    like `$schema` / `$ref` would otherwise be read as Kotlin references; we substitute
     *    `${'$'}` which renders as a literal `$`.
     */
    private fun tripleQuoted(value: String): String {
        val escaped = value
            .replace("$", "\${'\$'}")
            .replace("\"\"\"", "\"\"\${'\"'}")
        return "\"\"\"" + escaped + "\"\"\""
    }
}
